apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30950
    protocol: TCP
  selector:
    app: flask